android.useAndroidX=true
#I added this to fix a lint crash, can be removed afterwards
android.experimental.lint.version=8.13.2
android.newDsl=false
android.builtInKotlin=false
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.workers.max=1
org.gradle.parallel=false
android.enableJetifier=false
